### ISSUE TITLE
TriangularResidual not found in ima.residual

### ISSUE THREAD

**Issue by YuWLong666** [lgresele/independent-mechanism-analysis#3]
Hello, I have met a problem detailed ''TriangularResidual not found in ima.residual''.
Please tell me how to deal with that, Thanks.

**Comment by VincentStimper** [comment]
Hi @Yu-XiaoLong,

thanks for spotting this bug. We changed the name of the class and, apparently, did not refactor it correctly. I fixed it in [this commit](https://github.com/lgresele/independent-mechanism-analysis/commit/d4774c06efe6cc5675a43f1510d2cf370d83c4c4). Let us know if you still encounter any problems.

Best regards,
Vincent
